import Head from "next/head";
import CreateNewDocument from "../components/CreateNewDocument";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section className="bg-[#F8F9FA] pb-10 px-10 ">
        <div className="max-w-3xl mx-auto">
          <CreateNewDocument />
        </div>
      </section>
    </div>
  );
}
